language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: phpunit --configuration tests/phpunit.xml --coverage-clover=tests/coverage.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/coverage.xml

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
